### PR TITLE
[wip] Wwdc

### PR DESCRIPTION
**Pull request by chriseidhof**
Creating a PR so that we can easily see the differences. Please don't merge yet.

### CODE REVIEW

**Comment by JaviLorbada** [comment]
Just added all WWDC Videos 3498110, all slides c1eaee1 as suggested https://github.com/chriseidhof/ios-videos/issues/25#issuecomment-165788419, and speakers as well 5c5f0dd, speakers have no twitter yet. Shall we merge this @chriseidhof?

**Comment by chriseidhof** [comment]
Awesome! I rebased it and merged it into master. Thanks a lot!

**Comment by BalestraPatrick** [comment]
@JaviLorbada @chriseidhof The direct link of the WWDC videos point to the PDF only and once clicked, the slides are downloaded. Wouldn't it be better to point to the full page where the user can choose to watch the video, download the slides or just read the transcript? One link example would be: https://developer.apple.com/videos/play/wwdc2015-105/

**Comment by chriseidhof** [comment]
Yes! I just saw that after merging, but I changed it in bdb2851827a4e7974b26e3abc97d7e96140e0506. Now they link to apple.com.

**Comment by BalestraPatrick** [comment]
Looks good! 👌

**Pull request closed without merging**
