### PR TITLE
add 360iDev 2015 videos and speakers

### PR DESCRIPTION
**Pull request by jonfriskics**

### CODE REVIEW

**Comment by chriseidhof** [comment]
This looks really great! Would you mind adding some tags for the videos? This'll make it a lot easier for people to find them afterwards =)

**Comment by chriseidhof** [comment]
Also, I think the slug would be nicer (more consistent with the rest) if it were lowercase.

**Comment by jonfriskics** [comment]
Awesome!  Just made the slug fix and added some tags.

**Comment by johankj** [comment]
:+1: 
Could you squash them into one commit before we merge it? :)

**Comment by jonfriskics** [comment]
yep, done.

**Pull request merged**
