### PR TITLE
WWDC 2014

### PR DESCRIPTION
**Pull request by JaviLorbada**
Help wanted to fill out all the speakers within [videos.yml](https://github.com/chriseidhof/pomotv/commit/ae1929e7c0a69fbd5db98706fc706966511fa084#diff-9c972e16de8fdc102ef38e60c7d1e84dR135)

Speakers names can be found in the transcripts, i.e: http://asciiwwdc.com/2014/sessions/203

### CODE REVIEW

**Comment by JaviLorbada** [comment]
@chriseidhof anything else you think we should add into this? Otherwise I think it's ready to be merged.

**Comment by chriseidhof** [comment]
This is really great! I think the Craig Federighi twitter account is a parody account, if you remove that we can merge it in!

**Comment by JaviLorbada** [comment]
Didn't realise about that 😅

**Comment by chriseidhof** [comment]
Thanks!

**Pull request merged**
