### PR TITLE
Adding content for do{iOS} conference

### PR DESCRIPTION
**Pull request by Misantrofia**
Adding content for do{iOS} conference - http://do-ios.com/#!/home

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Looks good to me! Can you please squash the commits together? I'm going to merge afterwards 👍🏻

**Comment by Misantrofia** [comment]
I've squashed the commits.

**Comment by chriseidhof** [comment]
Awesome! Maybe one thing we could change: the edition is now "November 2015". We could change it to "2015" because it's the only edition that year. WDYT? Would you mind opening up another PR for this @Misantrofia ?

Thanks so much!

**Comment by Misantrofia** [comment]
No problem, I've added a new pull request for that.

**Pull request merged**
