### PR TITLE
NSLondon January 2016

### PR DESCRIPTION
**Pull request by douglashill**
This branch fixes a speaker’s name and adds NSLondon January 2016.

### CODE REVIEW

**Comment by JaviLorbada** [comment]
This looks awesome! Thanks! 🙇
Would you mind rebasing this before it gets merged?

**Comment by douglashill** [comment]
The readme says editions should be in date order, in which case the previous PR was wrong. (And I wouldn’t have a conflict there.)

Do you think it’s worth having a guideline to avoid conflicts (such as a recommended way of ordering videos and speakers) or are conflicts not as common as they seem to me?

**Comment by JaviLorbada** [comment]
You're totally right, it was my bad not check the Cocoalove order by date within the editions, I've solved that.

For the speakers there's no sorting rules at the moment, conflicts in this case are less likely to happen unless there's several PRs adding speakers at the same time. Could you then solve the speakers conflict? Sorry for the trouble in any case 🙇

**Comment by douglashill** [comment]
Done.

**Comment by JaviLorbada** [comment]
Thank you very much 👍

**Comment by chriseidhof** [comment]
Awesome =). I think it'd be nice to have something in there that checks whether the file is sorted... I'll try to write a lint step for this!

**Pull request merged**
