### PR TITLE
GitHub Reactive Cocoa Developer Conference & MCE Conference 2015

### PR DESCRIPTION
**Pull request by JaviLorbada**
- Add GitHub Reactive Cocoa Developer Conference 2014 fe6cd18
- Add iOS MCE Conference 2015 54188fd

### CODE REVIEW

**Comment by chriseidhof** [comment]
Hm, for some reason some speakers were removed? I think this must be by accident... Would you mind rebasing and not remove those speakers? Thanks a lot!

**Comment by JaviLorbada** [comment]
Totally my mistake, I've added the conferences information again and it seems to be ready now, thanks Chris! 🍻

**Comment by johankj** [comment]
@JaviLorbada: I can see that @chriseidhof has added slugs for events.
Would you mind adding slugs like "ghreact-2014" and "mceconf-2015" to the events? :)

**Comment by JaviLorbada** [comment]
@johankj sure thing, just added them 94b96ca, thanks for mentioning!

**Comment by chriseidhof** [comment]
Looks great! @johankj , do you want to try merging and publishing this? You should be able to do "rake publish" and it'll build the entire thing and push to gh-pages.

**Comment by chriseidhof** [comment]
Ah, we should add twitter info for Mike Lazer-Walker. Also, Marcus Zarra's name is Marcus S. Zarra here. We should probably consolidate that.

**Comment by JaviLorbada** [comment]
@chriseidhof just fixed that in #21 👌

**Pull request merged**
