### PR TITLE
[wip] Events and editions

### PR DESCRIPTION
**Pull request by chriseidhof**
Work on #54 

This currently is almost a "force rename" of event to edition. It makes things a bit weird currently, because there's no concept of events anymore. So that's the next step to add. As I made the changes, I started to get some doubt whether the terminology is right... but let's try to finish this and see what it's like.

TODO:
- [x] Add "events" concept
- [ ] Create "events" pages
- [x] Edition pages with spaces are now wrongly generated as `swift-summit/London%202015`, should be `swift-summit/london-2015`
- [x] Think whether the "/editions" page should be "/events" and what it's name should be.
- [ ] Remove duplication between the linter and video_helpers.rb (can we use a helper method in the Rakefile?)

I'm signing off for the day, if anyone wants to help do this just leave a comment (so that we won't do double work).

### CODE REVIEW

**Comment by eelco** [comment]
Regarding the third TODO item, I imagined editions as being children of events, and to have this also reflected in the URLs, for example, `/events/wwdc/2015`.

The `/events` page would then be the same as now, but link to all the different editions (at first).

**Comment by chriseidhof** [comment]
@eelco yes! But what do we do with editions that don't have an event? Or should we just always make sure that an edition has an event attached?

**Comment by eelco** [comment]
I’d think that conceptually it would be the other way around: an event that does not have editions. However, it’s not always easy to predict: a conference might have one edition, whether one follows might be unsure. Having to change URLs later (or do redirects) would not be optimal.

**Comment by eelco** [comment]
In the current dataset the only event without a year attached to it is “iOS Conf Singapore”. For now, let’s just give all events editions. It should be easy enough to attach a year or month-year.

**Comment by chriseidhof** [comment]
@eelco I've added events and editions to the data, however, things get super slow during debugging because the search takes 5s to build on my machine. Any ideas what this could be?

**Comment by eelco** [comment]
Good question, it already took a couple of seconds, I think? As a workaround, I would disable building the search index. (I guess the problem is that now search is available on each page it will always try to load the search index and therefore trigger building it? This is a problem in middleman server mode, right?)

**Comment by chriseidhof** [comment]
Yeah, I've moved it to the :build block in the Rakefile, but not sure if that's a good long-term solution. Maybe in development, we can load it lazily? Or somehow cache it?

**Comment by chriseidhof** [comment]
Okay, the page structure now looks like this:
- `/events/wwdc` (currently doesn't exist yet)
- `/events/wwdc/2015` (for an edition)
- `/events/wwdc/2015/speaker-title.html` (for a specific video)

**Comment by eelco** [comment]
Feel free to make a new issue regarding search slowing down development and assign it to me. I’ll do my best to look into it soon.

**Comment by eelco** [comment]
Okay, that was easy. `middleman-search` got updated last week and now has a ‘cache’ option to cache the index during development. I added the fix to this branch.

**Comment by chriseidhof** [comment]
I think we can just merge this in, and hopefully everything keeps working. I'll file an issue for event pages separately, for now this could just be a list of the editions.

**Pull request merged**
