### PR TITLE
Easier import for WWDC

### PR DESCRIPTION
**Pull request by JaviLorbada**
This needs approval since do not have speakers for the talks.
- The import has been done thanks to https://github.com/ASCIIwwdc/wwdc-session-transcripts.
- Description data has been added to `videos.yml`
- Events pages have been modified to look good without speakers.

### CODE REVIEW

**Comment by chriseidhof** [comment]
Oh, cool! I think it'd still be really helpful to add the speakers. The information is in the talks, I guess. Maybe we can split up the work among a few people? For example, everyone takes a year?

**Comment by JaviLorbada** [comment]
Agreed, let's do this all together 💪

Speakers info is usually in the transcript, i.e: http://asciiwwdc.com/2014/sessions/301, but sometimes is kinda difficult to find them.

**Comment by chriseidhof** [comment]
So maybe it's easiest to do this in multiple PRs? That way, whoever has time can pick up a single one? I'm sorry for the extra trouble, but I think the community will really benefit from this!

**Comment by JaviLorbada** [comment]
Do you prefer to merge this and complete the speakers later with smaller PRs? 

Or create new PRs for each year with all the info, event, videos, speakers?

**Comment by chriseidhof** [comment]
My thinking was to create a WIP PR for each year. Then we can assign those and someone can add the speakers for that year. Does that make sense? Or is it too much effort?

**Comment by JaviLorbada** [comment]
@chriseidhof could we merge 47ed7e5 and e901a24?

Then it's easier to create the other PRs. Thanks! :bow:

**Comment by chriseidhof** [comment]
I merged e901a2457fb103c930fe77514d2d619c56050616, but not the other commit. I think if we add speakers for each video, we won't need it. This way we get an error when there are no speakers, rather than silently fail!

**Comment by JaviLorbada** [comment]
Cool! Totally understand. I will create the other PRs in the meantime.

Shall we include also `description` information as in: https://github.com/chriseidhof/pomotv/commit/47ed7e54c61eb51b49e4cad51c5cc78615716564#diff-15105b1313061cab6e4e2d5b20e132f5R14

I dunno if we want to have that description only for WWDC or for the rest as well.

**Pull request closed without merging**
