### PR TITLE
Add NSLondon July

### PR DESCRIPTION
**Pull request by douglashill**

### CODE REVIEW

**Comment by douglashill** [comment]
This is good to go, although I’m expecting to need to resolve conflicts after https://github.com/chriseidhof/pomotv/pull/116 is merged. (It ought be be merged before this because it was submitted earlier.)

**Comment by chriseidhof** [comment]
Oh, I thought I merged that one already, sorry!

**Comment by douglashill** [comment]
I’ve rebased it. Ready to go.

**Comment by chriseidhof** [comment]
Thanks @douglashill !

**Pull request merged**
