### PR TITLE
CocoaHeads Stockholm 2015

### PR DESCRIPTION
**Pull request by MrAlek**
Added videos from various CocoaHeads Stockholm meetups during 2015. Felt like it didn't make sense to cut each meetup into its own event.

### CODE REVIEW

**Comment by johankj** [comment]
Thanks. :)
Let me get back to you on this one, when we have issue #54 handled.

**Comment by MrAlek** [comment]
Alright, didn't see it before posting. Love the initiative :)

**Comment by chriseidhof** [comment]
@MrAlek do you mind adding the dates of the individual videos? That way we can solve the rest separately =)

**Comment by MrAlek** [comment]
@chriseidhof Sure, just `date: 2015-11-08` like according to http://yaml.org/type/timestamp.html, right?

**Comment by chriseidhof** [comment]
That'd be perfect!

**Comment by JaviLorbada** [comment]
@MrAlek would you mind rebasing master into this? 

@chriseidhof shall we merge this to master before #70? To me this looks good after rebasing =)

**Comment by MrAlek** [comment]
@JaviLorbada Just rebased now.

**Comment by JaviLorbada** [comment]
@MrAlek thanks a lot! 🙇

**Comment by chriseidhof** [comment]
@JaviLorbada let's wait with merging until the events and editions stuff is in. Otherwise it's not really going to work, I think.

**Comment by JaviLorbada** [comment]
Cool let's wait till then =)

**Comment by chriseidhof** [comment]
I rebased and merged this in! Awesome work, thanks for all the patience. Now it's easy to add new editions of CocoaHeads. Happy New Year!

**Comment by MrAlek** [comment]
Thanks @chriseidhof & @JaviLorbada! Happy New Year!! :D :tada:

**Pull request closed without merging**
