### PR TITLE
Move search bar to top right

### PR DESCRIPTION
**Pull request by bontoJR**
I moved the search bar from the left side menu, to the main right side, always on top.

### CODE REVIEW

**Comment by bontoJR** [comment]
Result in the attache screenshot: 
screen shot 2015-12-22 at 10 01 38

**Comment by chriseidhof** [comment]
Wow, that makes it pretty prominent! I guess that will also force us to work on the search even more 😅. @eelco , wdyt?

**Comment by bontoJR** [comment]
Just after a week the website has too much videos to be surfed manually, discoverability has to be done right or finding the right video is going to be hard. 

The current design is minimal and ofc doesn't fit a lot of requirements of this kind of website, but I think moving the search bar it's a tiny-tiny improvement.

As soon as the website slows in PRs for content, I would suggest a nice discussion about how to improve discoverability: featured videos? voting system like HN or PH? shortlists (like: Functional Programming, FRP, Networking, Security, etc...)? Possibilities are infinite.

**Comment by eelco** [comment]
Hmm, I’m not a fan, sorry.

Okay, it’s big and on top of the page but:
- It’s no longer close to other navigation elements (and while it searches the whole site, that’s not what it implies when it’s on top of specific page).
- The contrast is lower and it looks like a header, not like a search field if it does not have focus.
- It scrolls off the page.
- It breaks the mobile layout (and it’s now lower on the page on mobile, where it’s arguably even more important).

The current design is a bit uncommon, with the header on the left hand side on desktop, but I think it would be better to be at least consistent with the design until it’s redesigned (#55).

I do agree that the design could definitely be improved though. It should be near the navigation, but it’s also weird that it’s part of it.

**Comment by singhamit089** [comment]
@bontoJR the search bar on the top is a good idea. https://cocoapods.org/ provides a good search experience for searching the pool of libraries, something similar can be done here with "Search As-You-Type Suggestions"

**Pull request merged**
