### PR TITLE
Added iOS Conf Singapore

### PR DESCRIPTION
**Pull request by BalestraPatrick**
Added iOS Conf Singapore (from #49). 

I also noticed that some tags are capitalized but most of them are lowercase. I changed the capitalized ones to lowercase to be consistent with the rest of the page.

If anyone could quickly give it a second look and then merge, that would be perfect!

### CODE REVIEW

**Comment by chriseidhof** [comment]
The URL should include the http://www part :)

**Comment by BalestraPatrick** [comment]
Oops, I knew I was missing something! Fixed now. 😃

**Comment by johankj** [comment]
Perhaps squash the commits into one before merging?

**Comment by chriseidhof** [comment]
That'd be nice indeed. Let's try to do it in the future =)

**Comment by johankj** [comment]
@chriseidhof:
Just FYI, it could still have been done before you merged it.
As seen [in this guide](https://github.com/ginatrapani/todo.txt-android/wiki/squash-all-commits-related-to-a-single-issue-into-a-single-commit) you can squash/rebase it locally and just do a force push. 
The pull request is connected to a specific branch – usually not the master-branch but it works just as well – and any changes to the branch will be shown in the pull request, even if you force push changes to the git history.

This is also the way pull requests are handled in the Swift repositories: [example](https://github.com/apple/swift/pull/549).

**Pull request merged**
